/** Generated by scripts/generate-event-v2-contract.ts. Do not edit. */
export const EVENT_V2_SCHEMA_DIGEST =
  "sha256:4cad573ea34b5372bc764d0e4826bc1aebb5424af21e11692015d027c855c6cd" as const;
export const EVENT_V2_GENERATED_CORE_TYPES = [
  "ledger.genesis",
  "session.started",
  "session.ended",
  "turn.started",
  "turn.completed",
  "tool.requested",
  "tool.completed",
] as const;
