/**
 * `harn backup`: restic-backed snapshots of `.harnery/`.
 *
 * Wraps `restic` with sensible defaults so single-user use doesn't require
 * remembering env vars. Repo path + password file live under XDG-style
 * paths and are init'd on first `harn backup init`. Subcommands:
 *
 *   init      restic init the repo (one-time)
 *   snapshot  restic backup of the durable, privacy-safe V3 state
 *   list      restic snapshots
 *   restore   restic restore <id>
 *   prune     restic forget --keep-daily 7 --keep-weekly 4 --prune
 *
 * Defaults (repo path, password file, and the keep-daily/weekly/monthly prune
 * policy) come from `.harnery/config.jsonc` `backup.*`, overridable per field by
 * env vars (HARNERY_RESTIC_REPO, HARNERY_RESTIC_PASSWORD_FILE) and CLI flags —
 * see `backupConfig()`. The wrapper deliberately doesn't try to abstract restic;
 * it surfaces it, with opinionated defaults plus passthrough after `--`.
 */

import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { Command } from "commander";
import type { EmitContext } from "../commander.ts";
import { backupConfig } from "../core/config.ts";

function defaultRepo(): string {
  return backupConfig().repo;
}

function defaultPasswordFile(): string {
  return backupConfig().passwordFile;
}

function findHarneryDir(): string | null {
  let dir = process.cwd();
  for (let i = 0; i < 8; i++) {
    if (existsSync(path.join(dir, ".harnery"))) {
      return path.join(dir, ".harnery");
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

function ensurePasswordFile(file: string): void {
  if (existsSync(file)) return;
  mkdirSync(path.dirname(file), { recursive: true });
  const pw = randomBytes(24).toString("base64");
  writeFileSync(file, `${pw}\n`, { encoding: "utf-8", mode: 0o600 });
}

interface RunOpts {
  repo?: string;
  passwordFile?: string;
  passThrough?: string[];
  stdio?: "inherit" | "pipe";
}

function runRestic(args: string[], opts: RunOpts = {}): { exitCode: number; stdout: string } {
  const repo = opts.repo ?? defaultRepo();
  const pwFile = opts.passwordFile ?? defaultPasswordFile();
  const wantInherit = opts.stdio === "inherit";
  const r = spawnSync("restic", [...args, ...(opts.passThrough ?? [])], {
    env: {
      ...process.env,
      RESTIC_REPOSITORY: repo,
      RESTIC_PASSWORD_FILE: pwFile,
    },
    encoding: "utf-8",
    stdio: wantInherit ? "inherit" : "pipe",
  });
  return {
    exitCode: r.status ?? 1,
    stdout: wantInherit ? "" : (r.stdout ?? "") + (r.stderr ?? ""),
  };
}

function checkRestic(emit: EmitContext): boolean {
  const r = spawnSync("restic", ["version"], { encoding: "utf-8" });
  if (r.status !== 0) {
    emit.error({
      code: "restic_missing",
      message: "restic is not on PATH",
      hint: "brew install restic (mac) / apt-get install restic (ubuntu) / https://restic.readthedocs.io/en/stable/020_installation.html",
    });
    return false;
  }
  return true;
}

interface BaseOpts {
  repo?: string;
  passwordFile?: string;
  json?: boolean;
}

export function registerBackupCommand(program: Command, emit: EmitContext): void {
  const backup = program
    .command("backup")
    .description("restic-backed snapshots of .harnery/ (multi-machine recovery insurance)");

  // -- init --
  backup
    .command("init")
    .description("Create the restic repository + password file (one-time).")
    .option("--repo <path>", `Repository path (default: ${defaultRepo()})`)
    .option(
      "--password-file <path>",
      `Password file (default: ${defaultPasswordFile()}, autogenerated)`,
    )
    .action((opts: BaseOpts) => {
      if (!checkRestic(emit)) {
        emit.setExitCode(1);
        return;
      }
      const repo = opts.repo ?? defaultRepo();
      const pwFile = opts.passwordFile ?? defaultPasswordFile();
      ensurePasswordFile(pwFile);
      mkdirSync(path.dirname(repo), { recursive: true });
      const r = runRestic(["init"], { repo, passwordFile: pwFile, stdio: "inherit" });
      if (r.exitCode === 0) {
        emit.text(`restic repo initialized at ${repo}\npassword file: ${pwFile}`);
      } else {
        emit.setExitCode(r.exitCode);
      }
    });

  // -- snapshot --
  backup
    .command("snapshot")
    .description(
      "Take a restic snapshot of the durable, privacy-safe V3 ledger and coordination state.",
    )
    .option("--tag <tag>", "Restic tag (repeatable)", collect, [] as string[])
    .option("--repo <path>", "Repository path")
    .option("--password-file <path>", "Password file")
    .option(
      "--include-artifacts",
      "Include managed working artifacts (default: excluded; potentially large + ephemeral)",
    )
    .action(
      (
        opts: BaseOpts & {
          tag: string[];
          includeArtifacts?: boolean;
        },
      ) => {
        if (!checkRestic(emit)) {
          emit.setExitCode(1);
          return;
        }
        const harnery = findHarneryDir();
        if (!harnery) {
          emit.error({
            code: "target_missing",
            message: "No .harnery/ found above cwd; run from an initialized project",
          });
          emit.setExitCode(1);
          return;
        }
        const passThrough: string[] = [];
        for (const t of opts.tag) {
          passThrough.push("--tag", t);
        }
        const safeTargets = [
          "ledgers",
          "councils",
          "journal",
          "work",
          "workflows",
          "decisions",
          "config.jsonc",
          ".name-history",
        ]
          .map((entry) => path.join(harnery, entry))
          .filter(existsSync);
        if (opts.includeArtifacts && existsSync(path.join(harnery, "artifacts"))) {
          safeTargets.push(path.join(harnery, "artifacts"));
        }
        if (safeTargets.length === 0) {
          emit.error({
            code: "backup_empty",
            message: "No durable V3 state is available to back up",
          });
          emit.setExitCode(1);
          return;
        }
        const r = runRestic(["backup", ...safeTargets], {
          repo: opts.repo,
          passwordFile: opts.passwordFile,
          stdio: "inherit",
          passThrough,
        });
        emit.setExitCode(r.exitCode);
      },
    );

  // -- list --
  backup
    .command("list")
    .description("List snapshots in the repo.")
    .option("--repo <path>", "Repository path")
    .option("--password-file <path>", "Password file")
    .option("--json", "JSON output")
    .action((opts: BaseOpts) => {
      if (!checkRestic(emit)) {
        emit.setExitCode(1);
        return;
      }
      const args = ["snapshots"];
      if (opts.json) args.push("--json");
      const r = runRestic(args, {
        repo: opts.repo,
        passwordFile: opts.passwordFile,
        stdio: opts.json ? "pipe" : "inherit",
      });
      if (opts.json && r.exitCode === 0) {
        try {
          emit.data(JSON.parse(r.stdout));
        } catch {
          emit.text(r.stdout);
        }
      }
      emit.setExitCode(r.exitCode);
    });

  // -- restore --
  backup
    .command("restore <snapshotId>")
    .description("Restore a snapshot to a target directory (default: ./restore-<timestamp>).")
    .option("--target <path>", "Restore destination")
    .option("--repo <path>", "Repository path")
    .option("--password-file <path>", "Password file")
    .action((snapshotId: string, opts: BaseOpts & { target?: string }) => {
      if (!checkRestic(emit)) {
        emit.setExitCode(1);
        return;
      }
      const target = opts.target ?? path.join(process.cwd(), `restore-${Date.now()}`);
      mkdirSync(target, { recursive: true });
      const r = runRestic(["restore", snapshotId, "--target", target], {
        repo: opts.repo,
        passwordFile: opts.passwordFile,
        stdio: "inherit",
      });
      if (r.exitCode === 0) {
        emit.text(`restored to: ${target}`);
      }
      emit.setExitCode(r.exitCode);
    });

  // -- prune --
  // Prune-policy defaults come from backup.keep_* in config.jsonc (falling back
  // to 7/4/6); an explicit --keep-* flag still overrides per invocation.
  const prunePolicy = backupConfig();
  backup
    .command("prune")
    .description(
      `Forget + prune snapshots (default policy: keep ${prunePolicy.keepDaily} daily / ${prunePolicy.keepWeekly} weekly / ${prunePolicy.keepMonthly} monthly).`,
    )
    .option("--keep-daily <n>", "Daily snapshots to keep", String(prunePolicy.keepDaily))
    .option("--keep-weekly <n>", "Weekly snapshots to keep", String(prunePolicy.keepWeekly))
    .option("--keep-monthly <n>", "Monthly snapshots to keep", String(prunePolicy.keepMonthly))
    .option("--dry-run", "Show what would be pruned without actually pruning")
    .option("--repo <path>", "Repository path")
    .option("--password-file <path>", "Password file")
    .action(
      (
        opts: BaseOpts & {
          keepDaily: string;
          keepWeekly: string;
          keepMonthly: string;
          dryRun?: boolean;
        },
      ) => {
        if (!checkRestic(emit)) {
          emit.setExitCode(1);
          return;
        }
        const args = [
          "forget",
          "--keep-daily",
          opts.keepDaily,
          "--keep-weekly",
          opts.keepWeekly,
          "--keep-monthly",
          opts.keepMonthly,
        ];
        if (!opts.dryRun) args.push("--prune");
        else args.push("--dry-run");
        const r = runRestic(args, {
          repo: opts.repo,
          passwordFile: opts.passwordFile,
          stdio: "inherit",
        });
        emit.setExitCode(r.exitCode);
      },
    );

  // -- check --
  backup
    .command("check")
    .description("restic check: verify repo integrity")
    .option("--repo <path>", "Repository path")
    .option("--password-file <path>", "Password file")
    .action((opts: BaseOpts) => {
      if (!checkRestic(emit)) {
        emit.setExitCode(1);
        return;
      }
      const r = runRestic(["check"], {
        repo: opts.repo,
        passwordFile: opts.passwordFile,
        stdio: "inherit",
      });
      emit.setExitCode(r.exitCode);
    });
}

function collect(value: string, acc: string[]): string[] {
  acc.push(value);
  return acc;
}
