/**
 * `harn backup`: restic-backed snapshots of `.harnery/`.
 *
 * Wraps `restic` with sensible defaults so single-user use doesn't require
 * remembering env vars. Repo path + password file live under XDG-style
 * paths and are init'd on first `harn backup init`. Subcommands:
 *
 *   init      restic init the repo (one-time)
 *   snapshot  restic backup .harnery/
 *   list      restic snapshots
 *   restore   restic restore <id>
 *   prune     restic forget --keep-daily 7 --keep-weekly 4 --prune
 *
 * Power users override via env vars (HARNERY_RESTIC_REPO, HARNERY_RESTIC_PASSWORD_FILE)
 * or by passing through any restic args after `--`. The wrapper deliberately
 * doesn't try to abstract restic; it surfaces it, with opinionated defaults plus
 * passthrough.
 */

import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import type { Command } from "commander";
import type { EmitContext } from "../commander.ts";

function defaultRepo(): string {
  const home = os.homedir();
  return process.env.HARNERY_RESTIC_REPO ?? path.join(home, ".cache", "harnery", "restic-repo");
}

function defaultPasswordFile(): string {
  const home = os.homedir();
  return (
    process.env.HARNERY_RESTIC_PASSWORD_FILE ??
    path.join(home, ".config", "harnery", "restic-password")
  );
}

function findHarneryDir(): string | null {
  let dir = process.cwd();
  for (let i = 0; i < 8; i++) {
    if (existsSync(path.join(dir, ".harnery"))) {
      return path.join(dir, ".harnery");
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

function ensurePasswordFile(file: string): void {
  if (existsSync(file)) return;
  mkdirSync(path.dirname(file), { recursive: true });
  const pw = randomBytes(24).toString("base64");
  writeFileSync(file, `${pw}\n`, { encoding: "utf-8", mode: 0o600 });
}

interface RunOpts {
  repo?: string;
  passwordFile?: string;
  passThrough?: string[];
  stdio?: "inherit" | "pipe";
}

function runRestic(args: string[], opts: RunOpts = {}): { exitCode: number; stdout: string } {
  const repo = opts.repo ?? defaultRepo();
  const pwFile = opts.passwordFile ?? defaultPasswordFile();
  const wantInherit = opts.stdio === "inherit";
  const r = spawnSync("restic", [...args, ...(opts.passThrough ?? [])], {
    env: {
      ...process.env,
      RESTIC_REPOSITORY: repo,
      RESTIC_PASSWORD_FILE: pwFile,
    },
    encoding: "utf-8",
    stdio: wantInherit ? "inherit" : "pipe",
  });
  return {
    exitCode: r.status ?? 1,
    stdout: wantInherit ? "" : (r.stdout ?? "") + (r.stderr ?? ""),
  };
}

function checkRestic(emit: EmitContext): boolean {
  const r = spawnSync("restic", ["version"], { encoding: "utf-8" });
  if (r.status !== 0) {
    emit.error({
      code: "restic_missing",
      message: "restic is not on PATH",
      hint: "brew install restic (mac) / apt-get install restic (ubuntu) / https://restic.readthedocs.io/en/stable/020_installation.html",
    });
    return false;
  }
  return true;
}

interface BaseOpts {
  repo?: string;
  passwordFile?: string;
  json?: boolean;
}

export function registerBackupCommand(program: Command, emit: EmitContext): void {
  const backup = program
    .command("backup")
    .description("restic-backed snapshots of .harnery/ (multi-machine recovery insurance)");

  // -- init --
  backup
    .command("init")
    .description("Create the restic repository + password file (one-time).")
    .option("--repo <path>", `Repository path (default: ${defaultRepo()})`)
    .option(
      "--password-file <path>",
      `Password file (default: ${defaultPasswordFile()}, autogenerated)`,
    )
    .action((opts: BaseOpts) => {
      if (!checkRestic(emit)) {
        emit.setExitCode(1);
        return;
      }
      const repo = opts.repo ?? defaultRepo();
      const pwFile = opts.passwordFile ?? defaultPasswordFile();
      ensurePasswordFile(pwFile);
      mkdirSync(path.dirname(repo), { recursive: true });
      const r = runRestic(["init"], { repo, passwordFile: pwFile, stdio: "inherit" });
      if (r.exitCode === 0) {
        emit.text(`restic repo initialized at ${repo}\npassword file: ${pwFile}`);
      } else {
        emit.setExitCode(r.exitCode);
      }
    });

  // -- snapshot --
  backup
    .command("snapshot")
    .description(
      "Take a restic snapshot of .harnery/ (excluding events.ndjson and " +
        ".lock files by default). Pass --target to back up a different path.",
    )
    .option("--target <path>", "Path to snapshot (default: .harnery/ from cwd walk-up)")
    .option("--tag <tag>", "Restic tag (repeatable)", collect, [] as string[])
    .option("--repo <path>", "Repository path")
    .option("--password-file <path>", "Password file")
    .option(
      "--include-events",
      "Don't exclude events.ndjson (default: excluded; large + machine-local)",
    )
    .action((opts: BaseOpts & { target?: string; tag: string[]; includeEvents?: boolean }) => {
      if (!checkRestic(emit)) {
        emit.setExitCode(1);
        return;
      }
      const target = opts.target ?? findHarneryDir();
      if (!target) {
        emit.error({
          code: "target_missing",
          message:
            "No .harnery/ found above cwd; pass --target explicitly or run from a monorepo with .harnery/",
        });
        emit.setExitCode(1);
        return;
      }
      const passThrough: string[] = [];
      if (!opts.includeEvents) {
        passThrough.push("--exclude", "events.ndjson");
        passThrough.push("--exclude", ".lock");
        passThrough.push("--exclude", ".log.lock");
      }
      for (const t of opts.tag) {
        passThrough.push("--tag", t);
      }
      const r = runRestic(["backup", target], {
        repo: opts.repo,
        passwordFile: opts.passwordFile,
        stdio: "inherit",
        passThrough,
      });
      emit.setExitCode(r.exitCode);
    });

  // -- list --
  backup
    .command("list")
    .description("List snapshots in the repo.")
    .option("--repo <path>", "Repository path")
    .option("--password-file <path>", "Password file")
    .option("--json", "JSON output")
    .action((opts: BaseOpts) => {
      if (!checkRestic(emit)) {
        emit.setExitCode(1);
        return;
      }
      const args = ["snapshots"];
      if (opts.json) args.push("--json");
      const r = runRestic(args, {
        repo: opts.repo,
        passwordFile: opts.passwordFile,
        stdio: opts.json ? "pipe" : "inherit",
      });
      if (opts.json && r.exitCode === 0) {
        try {
          emit.data(JSON.parse(r.stdout));
        } catch {
          emit.text(r.stdout);
        }
      }
      emit.setExitCode(r.exitCode);
    });

  // -- restore --
  backup
    .command("restore <snapshotId>")
    .description("Restore a snapshot to a target directory (default: ./restore-<timestamp>).")
    .option("--target <path>", "Restore destination")
    .option("--repo <path>", "Repository path")
    .option("--password-file <path>", "Password file")
    .action((snapshotId: string, opts: BaseOpts & { target?: string }) => {
      if (!checkRestic(emit)) {
        emit.setExitCode(1);
        return;
      }
      const target = opts.target ?? path.join(process.cwd(), `restore-${Date.now()}`);
      mkdirSync(target, { recursive: true });
      const r = runRestic(["restore", snapshotId, "--target", target], {
        repo: opts.repo,
        passwordFile: opts.passwordFile,
        stdio: "inherit",
      });
      if (r.exitCode === 0) {
        emit.text(`restored to: ${target}`);
      }
      emit.setExitCode(r.exitCode);
    });

  // -- prune --
  backup
    .command("prune")
    .description("Forget + prune snapshots (default policy: keep 7 daily / 4 weekly / 6 monthly).")
    .option("--keep-daily <n>", "Daily snapshots to keep", "7")
    .option("--keep-weekly <n>", "Weekly snapshots to keep", "4")
    .option("--keep-monthly <n>", "Monthly snapshots to keep", "6")
    .option("--dry-run", "Show what would be pruned without actually pruning")
    .option("--repo <path>", "Repository path")
    .option("--password-file <path>", "Password file")
    .action(
      (
        opts: BaseOpts & {
          keepDaily: string;
          keepWeekly: string;
          keepMonthly: string;
          dryRun?: boolean;
        },
      ) => {
        if (!checkRestic(emit)) {
          emit.setExitCode(1);
          return;
        }
        const args = [
          "forget",
          "--keep-daily",
          opts.keepDaily,
          "--keep-weekly",
          opts.keepWeekly,
          "--keep-monthly",
          opts.keepMonthly,
        ];
        if (!opts.dryRun) args.push("--prune");
        else args.push("--dry-run");
        const r = runRestic(args, {
          repo: opts.repo,
          passwordFile: opts.passwordFile,
          stdio: "inherit",
        });
        emit.setExitCode(r.exitCode);
      },
    );

  // -- check --
  backup
    .command("check")
    .description("restic check: verify repo integrity")
    .option("--repo <path>", "Repository path")
    .option("--password-file <path>", "Password file")
    .action((opts: BaseOpts) => {
      if (!checkRestic(emit)) {
        emit.setExitCode(1);
        return;
      }
      const r = runRestic(["check"], {
        repo: opts.repo,
        passwordFile: opts.passwordFile,
        stdio: "inherit",
      });
      emit.setExitCode(r.exitCode);
    });
}

function collect(value: string, acc: string[]): string[] {
  acc.push(value);
  return acc;
}
