import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import type { Command } from "commander";
import type { EmitContext } from "../commander.ts";
import { workflowSubscriptionOnly } from "../core/config.ts";
import { createBuiltinHarnessRegistry } from "../core/harnesses/index.ts";
import { findCoordRoot } from "../core/hooks/resolve/coord-root.ts";
import type { PolicyIsolation } from "../core/policy/index.ts";
import { loadPolicyFile } from "../core/policy/index.ts";
import {
  createSupervisor,
  listSupervisors,
  readSupervisor,
  runSupervisor,
  type SupervisorRecord,
  type SupervisorRunReport,
} from "../core/supervisor/index.ts";
import type { WorkflowSpecialistProfile } from "../core/workflow/index.ts";

interface CreateOpts {
  team: string;
  id?: string;
  title?: string;
  maxCycles?: string;
  maxRuntimeMs?: string;
  maxParallelWork?: string;
  maxTotalAttempts?: string;
  maxAgentsPerWork?: string;
  agentConcurrency?: string;
  acceptPassingProof?: boolean;
  resumeApproved?: boolean;
  retryBlocked?: boolean;
  json?: boolean;
}

interface RunOpts {
  harness?: string;
  cwd?: string;
  subscriptionOnly?: boolean;
  allowApiBilling?: boolean;
  policy?: string;
  isolation?: PolicyIsolation;
  approvalTo?: string;
  actor?: string;
  json?: boolean;
}

export function registerSupervisorCommand(program: Command, emit: EmitContext): void {
  const registry = createBuiltinHarnessRegistry();
  const supervisor = program
    .command("supervisor")
    .description("Run a bounded specialist team over a durable-work dependency graph.");

  supervisor
    .command("create <root-work-id>")
    .description("Freeze a goal, specialist team, automation policy, and execution limits.")
    .requiredOption("--team <file>", "JSON object mapping specialist ids to profiles")
    .option("--id <goal-id>", "Stable goal id (generated by default)")
    .option("--title <text>", "Goal title (defaults to root work title)")
    .option("--max-cycles <n>", "Foreground cycle ceiling (default 50)")
    .option("--max-runtime-ms <n>", "Foreground wall-time ceiling (default 14400000)")
    .option("--max-parallel-work <n>", "Concurrent work-item ceiling (default 1)")
    .option("--max-total-attempts <n>", "Graph-wide attempt ceiling (default 100)")
    .option("--max-agents-per-work <n>", "Child-agent ceiling per work item (default 20)")
    .option("--agent-concurrency <n>", "Child concurrency per work item (default 4)")
    .option("--accept-passing-proof", "Allow the supervisor to explicitly accept passing proof")
    .option("--no-resume-approved", "Stop after an approval instead of resuming its parked run")
    .option("--retry-blocked", "Allow bounded retry of blocked work")
    .option("--json", "Emit the complete supervisor record as JSON")
    .action((rootWorkId: string, opts: CreateOpts) => {
      withSupervisorRoot(emit, (coordRoot) => {
        const specialists = readTeamFile(opts.team);
        for (const [id, profile] of Object.entries(specialists)) {
          if (profile.harness && !registry.get(profile.harness)) {
            throw new Error(
              `specialist ${id} names unknown harness ${JSON.stringify(profile.harness)}`,
            );
          }
        }
        emitSupervisor(
          createSupervisor({
            coordRoot,
            rootWorkId,
            specialists,
            id: opts.id,
            title: opts.title,
            limits: {
              max_cycles: integer(opts.maxCycles),
              max_runtime_ms: integer(opts.maxRuntimeMs),
              max_parallel_work: integer(opts.maxParallelWork),
              max_total_attempts: integer(opts.maxTotalAttempts),
              max_agents_per_work: integer(opts.maxAgentsPerWork),
              agent_concurrency: integer(opts.agentConcurrency),
            },
            automation: {
              accept_passing_proof: opts.acceptPassingProof,
              resume_approved: opts.resumeApproved,
              retry_blocked: opts.retryBlocked,
            },
          }),
          opts.json,
          emit,
          true,
        );
      });
    });

  supervisor
    .command("list")
    .description("List durable goals and their derived next action.")
    .option("--json", "Emit complete supervisor records as JSON")
    .action((opts: { json?: boolean }) => {
      withSupervisorRoot(emit, (coordRoot) => {
        const records = listSupervisors(coordRoot);
        if (opts.json) {
          emit.config({ format: "json" });
          emit.data(records);
        } else if (records.length === 0) {
          emit.text("no durable supervisors\n");
        } else {
          emit.text(`${records.map(renderSupervisorRow).join("\n")}\n`);
        }
      });
    });

  supervisor
    .command("show <goal-id>")
    .description("Show one goal, frozen team, bounds, graph state, and next action.")
    .option("--json", "Emit the complete supervisor record as JSON")
    .action((goalId: string, opts: { json?: boolean }) => {
      withSupervisorRoot(emit, (coordRoot) => {
        emitSupervisor(readSupervisor(coordRoot, goalId), opts.json, emit, true);
      });
    });

  registerRunCommand(supervisor, "tick", registry, emit);
  registerRunCommand(supervisor, "run", registry, emit);
}

function registerRunCommand(
  supervisor: Command,
  mode: "tick" | "run",
  registry: ReturnType<typeof createBuiltinHarnessRegistry>,
  emit: EmitContext,
): void {
  supervisor
    .command(`${mode} <goal-id>`)
    .description(
      mode === "tick"
        ? "Perform at most one bounded scheduling cycle."
        : "Run bounded cycles until success, attention, no progress, or budget exhaustion.",
    )
    .option("--harness <name>", "Fallback harness for agent calls without a specialist")
    .option("--cwd <dir>", "Working directory for child agents")
    .option("--subscription-only", "Require stored harness-login billing")
    .option("--allow-api-billing", "Permit API-key override billing")
    .option("--policy <file>", "Host policy JSON/JSONC")
    .option("--isolation <mode>", "shared | worktree | sandbox | remote")
    .option("--approval-to <address>", "Address durable ASK requests")
    .option("--actor <name>", "Actor recorded on supervisor work decisions")
    .option("--json", "Emit the complete run report as JSON")
    .action(async (goalId: string, opts: RunOpts) => {
      await withSupervisorRootAsync(emit, async (coordRoot) => {
        if (opts.harness && !registry.get(opts.harness)) {
          throw new Error(`unknown harness ${JSON.stringify(opts.harness)}`);
        }
        const report = await runSupervisor({
          coordRoot,
          goalId,
          mode,
          actor: opts.actor,
          onLog: opts.json ? undefined : (line) => emit.text(`${line}\n`),
          engine: {
            spawners: registry.spawners(),
            defaultHarness: opts.harness,
            cwd: opts.cwd,
            subscriptionOnly:
              opts.subscriptionOnly === true ? true : workflowSubscriptionOnly(coordRoot),
            allowApiBilling: opts.allowApiBilling,
            harnessEvidence: Object.fromEntries(
              registry
                .list()
                .map((adapter) => [
                  adapter.profile.id,
                  { toolEvidence: adapter.profile.capabilities.toolEvidence },
                ]),
            ),
            policy: opts.policy ? loadPolicyFile(opts.policy) : undefined,
            approvalMode: "park",
            approvalAddressee: opts.approvalTo,
            isolation: opts.isolation,
            networkAccess: "enabled",
          },
        });
        emitSupervisorReport(report, opts.json, emit);
      });
    });
}

function readTeamFile(path: string): Record<string, WorkflowSpecialistProfile> {
  const absolute = resolve(path);
  let value: unknown;
  try {
    value = JSON.parse(readFileSync(absolute, "utf8"));
  } catch (error) {
    throw new Error(`cannot read supervisor team at ${absolute}: ${(error as Error).message}`);
  }
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error("supervisor team must be a JSON object keyed by specialist id");
  }
  return value as Record<string, WorkflowSpecialistProfile>;
}

function emitSupervisor(
  record: SupervisorRecord,
  json: boolean | undefined,
  emit: EmitContext,
  detail = false,
): void {
  if (json) {
    emit.config({ format: "json" });
    emit.data(record);
    return;
  }
  if (!detail) {
    emit.text(`${renderSupervisorRow(record)}\n`);
    return;
  }
  const projection = record.projection;
  const lines = [
    `${record.intent.id}: ${record.intent.title}`,
    `state: ${projection.state}`,
    `root: ${record.intent.root_work_id}`,
    `reason: ${projection.reason}`,
    `next: ${projection.next_action}`,
    `work: ${projection.work_ids.length}`,
    `attempts: ${projection.attempts_used}/${record.intent.limits.max_total_attempts}`,
    `specialists: ${projection.specialists.join(", ") || "none"}`,
    `automation: accept=${record.intent.automation.accept_passing_proof}, ` +
      `resume=${record.intent.automation.resume_approved}, retry=${record.intent.automation.retry_blocked}`,
  ];
  if (projection.attention_work.length) {
    lines.push(`attention: ${projection.attention_work.join(", ")}`);
  }
  emit.text(`${lines.join("\n")}\n`);
}

function emitSupervisorReport(
  report: SupervisorRunReport,
  json: boolean | undefined,
  emit: EmitContext,
): void {
  if (json) {
    emit.config({ format: "json" });
    emit.data(report);
    return;
  }
  emit.text(
    `supervisor ${report.goal_id}: ${report.stop_reason}\n` +
      `reason: ${report.reason}\n` +
      `cycles: ${report.cycles}; dispatches: ${report.dispatches}; acceptances: ${report.acceptances}\n` +
      `state: ${report.projection.state}; next: ${report.projection.next_action}\n`,
  );
}

function renderSupervisorRow(record: SupervisorRecord): string {
  const projection = record.projection;
  return `${record.intent.id}  ${projection.state.padEnd(20)}  ${projection.attempts_used}/${record.intent.limits.max_total_attempts}  ${projection.next_action.padEnd(18)}  ${record.intent.title}`;
}

function integer(value: string | undefined): number | undefined {
  if (value === undefined) return undefined;
  if (!/^\d+$/.test(value))
    throw new Error(`expected a positive integer, got ${JSON.stringify(value)}`);
  return Number.parseInt(value, 10);
}

function withSupervisorRoot(emit: EmitContext, fn: (coordRoot: string) => void): void {
  const coordRoot = findCoordRoot();
  if (!coordRoot) {
    emit.error({
      code: "no_coord_root",
      message: "no .harnery/ coordination root found; run `init` first",
    });
    emit.setExitCode(1);
    return;
  }
  try {
    fn(coordRoot);
  } catch (error) {
    emit.error({ code: "supervisor_failed", message: (error as Error).message });
    emit.setExitCode(1);
  }
}

async function withSupervisorRootAsync(
  emit: EmitContext,
  fn: (coordRoot: string) => Promise<void>,
): Promise<void> {
  const coordRoot = findCoordRoot();
  if (!coordRoot) {
    emit.error({
      code: "no_coord_root",
      message: "no .harnery/ coordination root found; run `init` first",
    });
    emit.setExitCode(1);
    return;
  }
  try {
    await fn(coordRoot);
  } catch (error) {
    emit.error({ code: "supervisor_failed", message: (error as Error).message });
    emit.setExitCode(1);
  }
}
