export {
  type AssertOp,
  type AssertResult,
  type AssertSpec,
  buildAssertCheck,
  parseAssertSpec,
} from "./asserts.js";
export {
  Browser,
  type BrowserOptions,
  BrowserSessionActionError,
  type BrowserSessionControl,
  type BrowserSessionInspection,
  type BrowserSessionLocator,
  type BrowserSessionNavigation,
  type BrowserSessionNavigationType,
  type BrowserSessionScreenshot,
  type BrowserSessionStatus,
  type BrowserSessionTab,
  type ConsoleEvent,
  type Diagnostics,
  type FailedRequest,
  type NavigateResult,
  type PageErrorEvent,
} from "./client.js";
export type {
  CheckRect,
  ContentAnnotationBox,
  ContentChecksRequest,
  ContentChecksResult,
  ContrastHit,
  ContrastResult,
  ImageHealthResult,
  ImageHit,
  PlaceholderHit,
  PlaceholderResult,
  TruncationHit,
  TruncationResult,
} from "./content-checks.js";
export {
  bandRects,
  type CritiqueCoverage,
  type CritiqueFinding,
  type CritiqueProvider,
  type CritiqueResult,
  type CritiqueTile,
  DEFAULT_CRITIQUE_RUBRIC,
  normalizeFindings,
  runCritique,
  tilesFromFullPage,
} from "./critique.js";
export {
  captureDevOverlay,
  type DevOverlayError,
  type DevOverlayResult,
} from "./dev-overlay.js";
export type {
  AlignChild,
  AlignCluster,
  AlignResult,
  ClipIssue,
  ClipResult,
  CrowdPair,
  CrowdResult,
  GapCluster,
  GapPair,
  GapResult,
  LayoutAxis,
  LayoutElementMeasurement,
  LayoutExclusion,
  LayoutLintRequest,
  LayoutLintResult,
  LayoutOutcome,
  LayoutRect,
  OverlapIssue,
  OverlapResult,
} from "./geometry.js";
export { buildLayoutLintCheck } from "./geometry.js";
export { isWSL, wslHeadedLaunchArgs } from "./launch-args.js";
export type {
  OverflowElement,
  OverflowResult,
  WidthResult,
} from "./layout.js";
export {
  serializeNetscapeCookies,
  writeNetscapeCookieFile,
} from "./netscape-cookies.js";
export {
  type JudgedContext,
  type JudgePageReviewPackOptions,
  type JudgePageReviewPackResult,
  judgePageReviewPack,
  toCritiqueRecords,
} from "./page-review-judge.js";
export {
  buildInspectionPlan,
  type FinalizePageReviewPackInput,
  finalizePageReviewPack,
  findingsSchemaDocument,
  listPackContexts,
  PAGE_REVIEW_FINDINGS_SCHEMA,
  PAGE_REVIEW_PACK_DIRNAME,
  PAGE_REVIEW_PACK_SCHEMA,
  type PageReviewContextCapture,
  type PageReviewContextRecord,
  type PageReviewCritiqueRecord,
  type PageReviewGateRecord,
  type PageReviewInspectionPlan,
  type PageReviewPackManifest,
  type PageReviewTileRecord,
  packPaths,
  readPackContext,
  readPackDom,
  readPackFullPage,
  readPackManifest,
  readPackSignature,
  readPackTiles,
  renderReviewMarkdown,
  writePackContext,
} from "./page-review-pack.js";
export {
  type BrowserProxy,
  type BrowserProxyGate,
  browserProxyFromEnv,
  browserProxyGateFromEnv,
  extractObservedIp,
  WEBRTC_PROXY_ONLY_ARG,
} from "./proxy.js";
export {
  buildQaManifest,
  type ChangeClass,
  type ClassifyOptions,
  classifySignatures,
  fnv1a32,
  type ManifestOptions,
  type QaClassification,
  type QaContext,
  type QaManifest,
  type QaNodeSignature,
  type QaScope,
  type QaSignature,
  type QaStylesheetSignature,
} from "./qa-plan.js";
export {
  defaultQaRunExec,
  QA_RUN_HEADLESS_ONLY_ENV,
  QA_RUN_RESULT_FILENAME,
  type QaRunExec,
  type QaRunExecOptions,
  type QaRunExecResult,
  type QaRunMatrixOptions,
  runQaMatrix,
} from "./qa-run.js";
export {
  computeVerdict,
  contextIdFor,
  mergeCoverage,
  QA_RUN_JOB_SCHEMA_VERSION,
  QA_RUN_RESULT_SCHEMA_VERSION,
  type QaRunBlocker,
  type QaRunCheck,
  type QaRunCommandOutcome,
  type QaRunContext,
  type QaRunCritiqueOutcome,
  type QaRunCritiquePool,
  type QaRunInteraction,
  type QaRunJob,
  type QaRunJobValidation,
  type QaRunPolicy,
  type QaRunResult,
  type QaRunReviewPack,
  type QaRunVerdict,
  validateQaRunJob,
} from "./qa-run-contracts.js";
export {
  listQaSnapshotTargets,
  loadQaSnapshot,
  QA_SNAPSHOT_DIR,
  type QaSnapshotStoreOptions,
  qaSnapshotKey,
  type ResolvedQaBaseline,
  resolveQaBaseline,
  type StoredQaSnapshot,
  saveQaSnapshot,
} from "./qa-snapshot.js";
export type {
  RuntHit,
  RuntsResult,
} from "./runts.js";
export {
  BROWSER_SESSION_MAX_FILL_BYTES,
  BROWSER_SESSION_MAX_FRAME_BYTES,
  BROWSER_SESSION_MAX_INSPECTION_TEXT_BYTES,
  BROWSER_SESSION_PROTOCOL_VERSION,
  type BrowserSessionDescriptor,
  BrowserSessionError,
  type BrowserSessionRequest,
  type BrowserSessionResponse,
  type BrowserSessionResult,
  type BrowserSessionServer,
  type BrowserSessionTarget,
  browserSessionTransport,
  readBrowserSessionDescriptor,
  sendBrowserSessionRequest,
  startBrowserSessionServer,
} from "./session-control.js";
export type {
  StandaloneHtmlRequest,
  StandaloneHtmlResult,
} from "./standalone-html.js";
export type {
  TargetSizeNode,
  TargetSizeOutcome,
  TargetSizeProfile,
  TargetSizeResult,
} from "./target-size.js";
export {
  bandOversizedRect,
  cutCost,
  type SnapOptions,
  type SnapSeam,
  snappedBandRects,
  type VisualAtom,
} from "./tiling.js";
export type {
  CheckVisibilityOptions,
  VisibilityResult,
  VisibilitySample,
} from "./visibility.js";
