import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { canonicalJsonV3 } from "../src/core/events/v3/canonical.ts";
import { EVENT_V3_CORE_EVENT_TYPES, EventV3Schema } from "../src/core/events/v3/contract.ts";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = resolve(repositoryRoot, "schemas/event-v3.schema.json");
const generatedPath = resolve(repositoryRoot, "src/core/events/v3/generated.ts");
const digest = `sha256:${createHash("sha256")
  .update(canonicalJsonV3(EventV3Schema))
  .digest("hex")}`;
const schemaBody = `${JSON.stringify(EventV3Schema, null, 2)}\n`;
const generatedTypes = EVENT_V3_CORE_EVENT_TYPES.map(
  (eventType) => `  ${JSON.stringify(eventType)},`,
).join("\n");
const generatedBody = `/** Generated by scripts/generate-event-v3-contract.ts. Do not edit. */\nexport const EVENT_V3_SCHEMA_DIGEST =\n  ${JSON.stringify(digest)} as const;\nexport const EVENT_V3_GENERATED_CORE_TYPES = [\n${generatedTypes}\n] as const;\n`;

const outputs = [
  [schemaPath, schemaBody],
  [generatedPath, generatedBody],
] as const;

if (process.argv.includes("--check")) {
  const drifted = outputs.filter(
    ([path, expected]) => !existsSync(path) || readFileSync(path, "utf8") !== expected,
  );
  if (drifted.length > 0) {
    for (const [path] of drifted) console.error(`generated V3 contract drift: ${path}`);
    process.exitCode = 1;
  }
} else {
  for (const [path, body] of outputs) writeFileSync(path, body, "utf8");
  console.log(`generated ${schemaPath}`);
  console.log(`schema digest ${digest}`);
}
