/**
 * Install-side owner of the OpenCode plugin files: what `harn init --adapter
 * opencode` writes, what `--check`/`doctor` compare against, and what `deinit`
 * removes. The plugin itself lives in `opencode-plugin/src/index.ts` and is
 * copied verbatim under a hash-stamped ownership header, the same fully-owned
 * file contract as the shipped skills (`lib/instructions/splice.ts`).
 *
 * Layout under the project root (`ADAPTER_SPECS.opencode.settingsFile` names
 * the entry file):
 *
 *   .opencode/plugins/harnery/index.ts    # the plugin, header + verbatim source
 *   .opencode/plugins/harnery/harnery.json # { schema, agentHook } written by init
 *
 * OpenCode auto-discovers every directory under `.opencode/plugins/`, so no
 * `opencode.json` edit is needed and a configured-plugin entry is never
 * written (OpenCode also refuses a configured local *file*; only directories
 * load that way).
 */

import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { shortHash } from "../../../lib/instructions/splice.ts";
import { ADAPTER_SPECS } from "./events.ts";

export const OPENCODE_PLUGIN_ENTRY = ADAPTER_SPECS.opencode.settingsFile;
export const OPENCODE_PLUGIN_DIR = dirname(OPENCODE_PLUGIN_ENTRY);
export const OPENCODE_PLUGIN_CONFIG = `${OPENCODE_PLUGIN_DIR}/harnery.json`;
export const OPENCODE_PLUGIN_CONFIG_SCHEMA = "harnery-opencode-plugin/v1";

const HEADER_RE = /^\/\/ harnery:generated opencode-plugin v=([0-9a-f]{8});[^\n]*\n/;

/** Package-relative path of the shipped plugin source (also listed in `files`). */
const PLUGIN_SOURCE = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
  "..",
  "opencode-plugin",
  "src",
  "index.ts",
);

/** The plugin source as shipped, trimmed so header + body hashing is stable. */
export function openCodePluginSource(): string {
  return readFileSync(PLUGIN_SOURCE, "utf8").trim();
}

/** Render the installed entry file: ownership header, then the verbatim source. */
export function renderOpenCodePluginEntry(
  binName: string,
  source = openCodePluginSource(),
): string {
  const body = source.trim();
  const header =
    `// harnery:generated opencode-plugin v=${shortHash(body)}; machine-owned; ` +
    `regenerated by \`${binName} init --adapter opencode\`, removed by \`${binName} deinit --adapter opencode\`. ` +
    "Edit harnery's opencode-plugin/src/index.ts, not this file.";
  return `${header}\n${body}\n`;
}

/** Render the sibling config the plugin reads to find the `agent-hook` launcher. */
export function renderOpenCodePluginConfig(agentHook: string): string {
  return `${JSON.stringify({ schema: OPENCODE_PLUGIN_CONFIG_SCHEMA, agentHook }, null, 2)}\n`;
}

/** True when the content carries harnery's plugin ownership header. */
export function isOwnedOpenCodePlugin(content: string): boolean {
  return HEADER_RE.test(content);
}

export type OpenCodePluginStatus = "missing" | "fresh" | "stale" | "foreign";

export interface OpenCodePluginCheck {
  status: OpenCodePluginStatus;
  /** Human-readable drift reasons, one per problem; empty when fresh or missing. */
  issues: string[];
}

/**
 * Compare the installed plugin files with what init would write now. Pure
 * except for reads; never writes. `foreign` means an entry file exists at the
 * harnery path without harnery's header, which init refuses to overwrite.
 */
export function checkOpenCodePlugin(
  projectRoot: string,
  expected: { binName: string; agentHook: string; source?: string },
): OpenCodePluginCheck {
  const entryPath = resolve(projectRoot, OPENCODE_PLUGIN_ENTRY);
  const configPath = resolve(projectRoot, OPENCODE_PLUGIN_CONFIG);
  if (!existsSync(entryPath)) return { status: "missing", issues: [] };
  const content = readFileSync(entryPath, "utf8");
  const match = HEADER_RE.exec(content);
  if (!match) {
    return {
      status: "foreign",
      issues: [`${OPENCODE_PLUGIN_ENTRY}: exists without harnery's ownership header`],
    };
  }
  const issues: string[] = [];
  const body = content.slice(match[0].length).trim();
  const fresh = (expected.source ?? openCodePluginSource()).trim();
  if (match[1] !== shortHash(fresh) || body !== fresh) {
    issues.push(`${OPENCODE_PLUGIN_ENTRY}: plugin source is stale (re-run init)`);
  }
  if (!existsSync(configPath)) {
    issues.push(`${OPENCODE_PLUGIN_CONFIG}: missing`);
  } else if (readFileSync(configPath, "utf8") !== renderOpenCodePluginConfig(expected.agentHook)) {
    issues.push(`${OPENCODE_PLUGIN_CONFIG}: stale agent-hook launcher (re-run init)`);
  }
  return { status: issues.length === 0 ? "fresh" : "stale", issues };
}

export interface OpenCodePluginInstall {
  actions: string[];
  /** Set when init must stop: a foreign file sits at the harnery path. */
  error?: string;
}

/** Write (or refresh) the plugin directory. Idempotent; a fresh install is a no-op. */
export function installOpenCodePlugin(
  projectRoot: string,
  opts: { binName: string; agentHook: string; dryRun: boolean },
): OpenCodePluginInstall {
  const check = checkOpenCodePlugin(projectRoot, opts);
  if (check.status === "foreign") {
    return {
      actions: [],
      error:
        `✗ ${OPENCODE_PLUGIN_ENTRY} exists but is not harnery's plugin; refusing to overwrite. ` +
        "Move it aside and re-run.",
    };
  }
  if (check.status === "fresh") {
    return { actions: [`· opencode plugin already installed at ${OPENCODE_PLUGIN_DIR}/`] };
  }
  const verb = check.status === "missing" ? "install" : "refresh";
  if (opts.dryRun) {
    return {
      actions: [
        `+ would ${verb} the opencode plugin at ${OPENCODE_PLUGIN_DIR}/ (index.ts + harnery.json)`,
        ...check.issues.map((issue) => `  · ${issue}`),
      ],
    };
  }
  const dir = resolve(projectRoot, OPENCODE_PLUGIN_DIR);
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    resolve(projectRoot, OPENCODE_PLUGIN_ENTRY),
    renderOpenCodePluginEntry(opts.binName),
  );
  writeFileSync(
    resolve(projectRoot, OPENCODE_PLUGIN_CONFIG),
    renderOpenCodePluginConfig(opts.agentHook),
  );
  return {
    actions: [
      `+ ${verb === "install" ? "installed" : "refreshed"} the opencode plugin at ${OPENCODE_PLUGIN_DIR}/ (index.ts + harnery.json)`,
    ],
  };
}

/** Remove the plugin directory when harnery owns it. Leaves a foreign file alone. */
export function removeOpenCodePlugin(projectRoot: string, dryRun: boolean): string[] {
  const dir = resolve(projectRoot, OPENCODE_PLUGIN_DIR);
  const entryPath = resolve(projectRoot, OPENCODE_PLUGIN_ENTRY);
  if (!existsSync(entryPath)) {
    return [`· ${OPENCODE_PLUGIN_DIR}/ doesn't exist; no plugin to remove`];
  }
  if (!isOwnedOpenCodePlugin(readFileSync(entryPath, "utf8"))) {
    return [`· ${OPENCODE_PLUGIN_ENTRY} is not harnery's plugin; left in place`];
  }
  if (dryRun) return [`+ would remove ${OPENCODE_PLUGIN_DIR}/ (harnery-owned plugin)`];
  rmSync(dir, { recursive: true, force: true });
  return [`+ removed ${OPENCODE_PLUGIN_DIR}/ (harnery-owned plugin)`];
}
