/**
 * Locks the install-side contract for the OpenCode plugin: init writes an
 * owned entry + config, --check sees hand edits and launcher drift, a foreign
 * file at the harnery path is never overwritten, and deinit removes only what
 * harnery owns.
 */

import { afterEach, describe, expect, test } from "bun:test";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  checkOpenCodePlugin,
  installOpenCodePlugin,
  isOwnedOpenCodePlugin,
  OPENCODE_PLUGIN_CONFIG,
  OPENCODE_PLUGIN_DIR,
  OPENCODE_PLUGIN_ENTRY,
  openCodePluginSource,
  removeOpenCodePlugin,
  renderOpenCodePluginConfig,
  renderOpenCodePluginEntry,
} from "./opencode-plugin.ts";

const roots: string[] = [];
function root(): string {
  const dir = mkdtempSync(join(tmpdir(), "harnery-oc-install-"));
  roots.push(dir);
  return dir;
}
afterEach(() => {
  for (const dir of roots.splice(0)) rmSync(dir, { recursive: true, force: true });
});

const EXPECTED = { binName: "harn", agentHook: "harnery/bin/agent-hook" };

describe("OpenCode plugin install files", () => {
  test("the shipped source is self-contained: node builtins only, no relative or package imports", () => {
    const source = openCodePluginSource();
    const imports = [...source.matchAll(/^import .* from "([^"]+)";?$/gm)].map((m) => m[1]!);
    expect(imports.length).toBeGreaterThan(0);
    for (const specifier of imports) expect(specifier.startsWith("node:")).toBe(true);
    expect(source).toContain("export default createHarneryOpenCodePlugin()");
  });

  test("renders an owned entry whose header hash covers the verbatim source", () => {
    const entry = renderOpenCodePluginEntry("acme", "export default { id: 'x' }");
    expect(entry.split("\n")[0]).toMatch(
      /^\/\/ harnery:generated opencode-plugin v=[0-9a-f]{8}; machine-owned; regenerated by `acme init --adapter opencode`, removed by `acme deinit --adapter opencode`\./,
    );
    expect(entry.endsWith("export default { id: 'x' }\n")).toBe(true);
    expect(isOwnedOpenCodePlugin(entry)).toBe(true);
    expect(isOwnedOpenCodePlugin("export default {}")).toBe(false);
  });

  test("renders the launcher config", () => {
    expect(JSON.parse(renderOpenCodePluginConfig("agent-hook"))).toEqual({
      schema: "harnery-opencode-plugin/v1",
      agentHook: "agent-hook",
    });
  });

  test("install → fresh → idempotent, and a re-run after drift refreshes", () => {
    const dir = root();
    expect(checkOpenCodePlugin(dir, EXPECTED)).toEqual({ status: "missing", issues: [] });

    const dry = installOpenCodePlugin(dir, { ...EXPECTED, dryRun: true });
    expect(dry.actions[0]).toContain("would install");
    expect(existsSync(join(dir, OPENCODE_PLUGIN_ENTRY))).toBe(false);

    const first = installOpenCodePlugin(dir, { ...EXPECTED, dryRun: false });
    expect(first.actions).toEqual([
      `+ installed the opencode plugin at ${OPENCODE_PLUGIN_DIR}/ (index.ts + harnery.json)`,
    ]);
    expect(readFileSync(join(dir, OPENCODE_PLUGIN_ENTRY), "utf8")).toBe(
      renderOpenCodePluginEntry("harn"),
    );
    expect(readFileSync(join(dir, OPENCODE_PLUGIN_CONFIG), "utf8")).toBe(
      renderOpenCodePluginConfig(EXPECTED.agentHook),
    );
    expect(checkOpenCodePlugin(dir, EXPECTED)).toEqual({ status: "fresh", issues: [] });

    const second = installOpenCodePlugin(dir, { ...EXPECTED, dryRun: false });
    expect(second.actions).toEqual([
      `· opencode plugin already installed at ${OPENCODE_PLUGIN_DIR}/`,
    ]);

    // A hand edit to the body is stale even though the header survived.
    const entryPath = join(dir, OPENCODE_PLUGIN_ENTRY);
    writeFileSync(entryPath, `${readFileSync(entryPath, "utf8")}\n// local tweak\n`);
    const stale = checkOpenCodePlugin(dir, EXPECTED);
    expect(stale.status).toBe("stale");
    expect(stale.issues).toEqual([
      `${OPENCODE_PLUGIN_ENTRY}: plugin source is stale (re-run init)`,
    ]);

    // A moved launcher is stale via the config.
    const moved = checkOpenCodePlugin(dir, { binName: "harn", agentHook: "agent-hook" });
    expect(moved.issues).toContain(
      `${OPENCODE_PLUGIN_CONFIG}: stale agent-hook launcher (re-run init)`,
    );

    const refreshed = installOpenCodePlugin(dir, { ...EXPECTED, dryRun: false });
    expect(refreshed.actions[0]).toContain("refreshed");
    expect(checkOpenCodePlugin(dir, EXPECTED).status).toBe("fresh");
  });

  test("a missing config is reported and repaired", () => {
    const dir = root();
    installOpenCodePlugin(dir, { ...EXPECTED, dryRun: false });
    rmSync(join(dir, OPENCODE_PLUGIN_CONFIG));
    expect(checkOpenCodePlugin(dir, EXPECTED)).toEqual({
      status: "stale",
      issues: [`${OPENCODE_PLUGIN_CONFIG}: missing`],
    });
    installOpenCodePlugin(dir, { ...EXPECTED, dryRun: false });
    expect(existsSync(join(dir, OPENCODE_PLUGIN_CONFIG))).toBe(true);
  });

  test("a foreign file at the harnery path is refused by install and left alone by remove", () => {
    const dir = root();
    mkdirSync(join(dir, OPENCODE_PLUGIN_DIR), { recursive: true });
    writeFileSync(join(dir, OPENCODE_PLUGIN_ENTRY), "export default { id: 'mine', setup() {} }\n");
    const check = checkOpenCodePlugin(dir, EXPECTED);
    expect(check.status).toBe("foreign");
    const install = installOpenCodePlugin(dir, { ...EXPECTED, dryRun: false });
    expect(install.error).toContain("refusing to overwrite");
    expect(readFileSync(join(dir, OPENCODE_PLUGIN_ENTRY), "utf8")).toContain("id: 'mine'");
    expect(removeOpenCodePlugin(dir, false)).toEqual([
      `· ${OPENCODE_PLUGIN_ENTRY} is not harnery's plugin; left in place`,
    ]);
    expect(existsSync(join(dir, OPENCODE_PLUGIN_ENTRY))).toBe(true);
  });

  test("remove deletes the owned directory, dry-run previews, absent is a no-op", () => {
    const dir = root();
    expect(removeOpenCodePlugin(dir, false)).toEqual([
      `· ${OPENCODE_PLUGIN_DIR}/ doesn't exist; no plugin to remove`,
    ]);
    installOpenCodePlugin(dir, { ...EXPECTED, dryRun: false });
    expect(removeOpenCodePlugin(dir, true)).toEqual([
      `+ would remove ${OPENCODE_PLUGIN_DIR}/ (harnery-owned plugin)`,
    ]);
    expect(existsSync(join(dir, OPENCODE_PLUGIN_ENTRY))).toBe(true);
    expect(removeOpenCodePlugin(dir, false)).toEqual([
      `+ removed ${OPENCODE_PLUGIN_DIR}/ (harnery-owned plugin)`,
    ]);
    expect(existsSync(join(dir, OPENCODE_PLUGIN_DIR))).toBe(false);
  });
});
